[package]
name = "raug"
description = "raug - Rusty AUdio Graphs"
license = "Apache 2.0 OR MIT"
version = "0.1.0"
edition = "2021"

[lib]
name = "raug"

[features]
default = []
jack = ["cpal/jack"]
mem2g = []
mem4g = []
mem8g = []

[workspace]
members = ["raug-iced", "raug-lua"]

[dependencies]
cpal = { version = "0.15.3", features = [] }
itertools = "0.13.0"
log = "0.4.22"
petgraph = { version = "0.6.5", features = ["serde-1"] }
hound = "3.5"
thiserror = "1.0"
downcast-rs = "1.2.1"
serde = { version = "1", features = ["derive"] }
erased-serde = "0.4.5"
typetag = "0.2.18"

[dev-dependencies]
env_logger = "0.11"
