[package]
name = "daprs"
version = "0.1.0"
edition = "2021"

[lib]
name = "daprs"

[features]
default = []
jack = ["cpal/jack"]

[workspace]
members = ["daprs-macros"]

[dependencies]
cpal = { version = "0.15.3", features = [] }
itertools = "0.13.0"
log = "0.4.22"
petgraph = "0.6.5"
hound = "3.5"
thiserror = "1.0.63"
downcast-rs = "1.2.1"

[dependencies.daprs-macros]
path = "daprs-macros"

[dev-dependencies]
env_logger = "0.11"

[[example]]
name = "demo"
path = "examples/demo.rs"
